joint_limits:
  joint1:
    has_position_limits: true

    has_velocity_limits: true
    max_velocity: 30.
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0

    k_position: 2
    k_velocity: 1
    ####### LanPi #######
    # min_position: 159.0
    # max_position: 235.0
    # soft_min_position: 160.0
    # soft_max_position: 230.0
    ####### LarTi #######
    min_position: 185.0
    max_position: 265.0
    soft_min_position: 190.0
    soft_max_position: 260.0
    ####### Riyad #######
    # min_position: 159.0
    # max_position: 235.0
    # soft_min_position: 160.0
    # soft_max_position: 230.0