#
#  ### Params of the ARMMS RPI node ###
#
rpi_loop_rate               : 100 # Hz
diag_loop_rate              : 1   # Hz
# Pin definition using Raspberry Pi numbering
user_btn_up_pin             : 24
user_btn_down_pin           : 25
power_button_pin            : 23
switch_limit_pin            : 7
red_led_pin                 : 0
green_led_pin               : 2
blue_led_pin                : 3
motor_power_pin             : 12

# duration of a long press on power button
long_press_duration         : 4.0

