topics:
- /armms_control/lower_limit
- /armms_control/upper_limit
- /armms_control/velocity_setpoint
- /armms_rpi/motor_power
- /armms_rpi/switch_limit
- /armms_rpi/user_button_down
- /armms_rpi/user_button_up
- /armms_webgui/user_button_down
- /armms_webgui/user_button_up
- /at1x/controller/position/joint1/command
- /joint_states

